apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  labels:
    app: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: localhost:5000/employee-app:0.0.1
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username 
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password 
            - name: ATLAS_URI
              value: "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo-nodeport-svc:32000"          
          ports:
            - containerPort: 3000
              name: employee-app
---
apiVersion: v1
kind: Service
metadata:
  name: employee-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: employee-app
  selector:
    app: employee-app
